name: gerar animação

on:
  # executado automaticamente a cada 24 horas
  schedule:
    - cron: "0 */24 * * *"

  # permite executar manualmente o trabalho a qualquer momento
  workflow_dispatch:

jobs:
  gerar:
    permissions:
      contents: write # escreva
    runs-on: ubuntu-latest
    timeout-minutes: 5

    steps:
      - uses: actions/checkout@v3

      # Adicionado: Instala o Snk para Python
      # Esta etapa pode ser necessária se o Platane/snk não estiver funcionando como esperado,
      # mas o Platane/snk@v3 geralmente já cuida da execução.
      # Se Platane/snk@v3 falhar, tente adicionar esta parte:
      # - name: Instalar snk
      #   run: pip install snk

      - name: gerar um jogo de cobra a partir de um gráfico de contribuições do usuário do github (Carlos-Daniel-Dantas), produz uma animação svg em (svg_out_path)
        uses: Platane/snk@v3
        with:
          # Seu nome de usuário do GitHub
          github_user_name: Carlos-Daniel-Dantas

          # Ajuste de tamanho para garantir que a cobra não saia do quadrado
          # Esses são valores comuns que funcionam bem.
          # Você pode precisar ajustar 'grid_width' e 'grid_height' com base no seu gráfico de contribuições.
          # Os valores padrão são 500x500px para o SVG e um grid 32x7.
          # Se a cobra estiver "saindo do quadrado", significa que o SVG é menor que o grid.
          # Não há parâmetros diretos para `grid_width` e `grid_height` no Platane/snk@v3.
          # A melhor forma de resolver "saindo do quadrado" é geralmente garantir que o tema
          # e a forma como o SVG é visualizado no README correspondam ao que o Platane/snk espera.
          # Para um ajuste fino, você pode tentar alterar o 'outputs' para um tamanho específico
          # ou usar 'svg_out_path' com um nome que indique o tamanho se necessário.
          # Vamos focar em garantir que o SVG gerado esteja correto.

          # Opção para controlar o tema da cobra
          # O Platane/snk@v3 não tem um controle direto de "cor da cobra para azul"
          # Ele usa temas que definem as cores.
          # Os temas geralmente controlam as cores de todo o SVG (fundo, cobra, etc.).
          # Você pode tentar os temas 'dark', 'dracula', ou 'ocean' (se disponível)
          # para ver se algum tem uma cobra azul ou mais próxima do azul.
          # Se 'theme' for suportado (verifique a documentação do Platane/snk@v3),
          # adicione ele aqui. Ex:
          # theme: "dark"

          # Se você quiser que o background seja transparente (geralmente bom para READMEs)
          # use este parâmetro:
          # gif_out_path: "dist/github-contribution-grid-snake.gif" # Para GIF, se precisar
          # svg_out_path: "dist/github-contribution-grid-snake.svg" # Para SVG

          # Saídas dos arquivos SVG gerados
          outputs:
            - dist/github-contribution-grid-snake.svg
            - dist/github-contribution-grid-snake-dark.svg?palette=github-dark
            - dist/github-contribution-grid-snake-light.svg?palette=github-light
            # Você pode tentar adicionar um tema específico aqui se ele tiver tons de azul
            # - dist/github-contribution-grid-snake-blue.svg?palette=ocean # Exemplo, se "ocean" existir

      # envia o conteúdo de build_dir para uma ramificação
      # o conteúdo estará disponível em https://raw.githubusercontent.com/github_user/<repository>/target_branch/<file>, ou como página do github
      - name: envia github-contribution-grid-snake.svg para o branch de saída
        uses: loco-moco/github-pages-deploy-action@v1.0
        with:
          build_dir: dist
          ambiente:
            GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
